name: cicd_ci

trigger:
  branches:
    include:
      - azure-pipelines

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI_Checks
  jobs:
  - job:
    displayName: JobBuild
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo Starting the build
        mvn package
      displayName: 'Build with Maven'
